channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=23.1.2
- pip:
  - mlflow==2.9.1
  - cloudpickle==3.0.0
  - numpy==1.26.1
  - packaging==23.0
  - psutil==5.9.5
  - pyyaml==6.0
  - scikit-learn==1.3.2
  - scipy==1.10.1
name: mlflow-env
